### ISSUE TITLE
Improve side image on RTE

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1294]
The button "side image" on the image toolbar of RTE has the same effect as right aligned image.

![image](https://user-images.githubusercontent.com/931642/130686031-71c679f9-519f-4458-b887-d442519f09b7.png)

Is it possible to add an option to float the image to the left, but without the `clear` property? This way, a row of images could be made.

Thank you!

**Comment by intoeetive** [comment]
@robsonsobral the styles are the same there indeed: https://github.com/ckeditor/ckeditor5-image/blob/master/theme/imagestyle.css
Can you think of what exact updates to the CSS need to be made?

**Comment by robsonsobral** [comment]
Because we have:

```css
.ck-content .image {
  display: table;
  clear: both;
  text-align: center;
  margin: 1em auto
}

```

I think they should change to:

```css
.ck-content {

  & .image-style-side,
  & .image-style-align-left,
  & .image-style-align-center,
  & .image-style-align-right {
    max-width: 50%;
  }

  & .image-style-side {
    /* float: right; */
    float: left;
    /* margin-left: var(--ck-image-style-spacing); */
    margin-right: var(--ck-image-style-spacing);

    /* the important part */
    clear: none; 
  }

  & .image-style-align-left {
    float: left;
    margin-right: var(--ck-image-style-spacing);
  }

  & .image-style-align-center {
    margin-left: auto;
    margin-right: auto;
  }

  & .image-style-align-right {
    float: right;
    margin-left: var(--ck-image-style-spacing);
  }
}
```

If you want, @intoeetive , I can draw a new icon.
