### ISSUE TITLE
Menu of sites overflows without scrollbars

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1346]
I have 49 sites (for now) on MSM and the menu is toooooo tall for the window.

The file common.min.css needs:

```css
.dropdown,
.select__dropdown {
  max-height: 90vh;
  overflow-y: auto;
}
```
